name: CI

on:
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: 6.0.x
  REDDIT__CLIENTID: ${{ secrets.REDDIT__CLIENTID }}
  REDDIT__CLIENTSECRET: ${{ secrets.REDDIT__CLIENTSECRET }}
  REDDIT__PASSWORD: ${{ secrets.REDDIT__PASSWORD }}
  REDDIT__USERNAME: ${{ secrets.REDDIT__USERNAME }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Analyze code
        run: dotnet format --no-restore --verify-no-changes --severity info
      - name: Build
        run: dotnet build --no-restore
      - name: Run tests
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.9
        with:
          reports: '**/coverage.cobertura.xml'
          targetdir: coveragereport
          reporttypes: 'Html;MarkdownSummary'
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: CoverageReport      
          path: coveragereport
      # - name: Add coverage comment
      #   uses: marocchino/sticky-pull-request-comment@v2
      #   with:
      #     recreate: true
      #     path: code-coverage-results.md
