name: CI

on:
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: 6.0.x
  REDDIT__CLIENTID: ${{ secrets.REDDIT__CLIENTID }}
  REDDIT__CLIENTSECRET: ${{ secrets.REDDIT__CLIENTSECRET }}
  REDDIT__PASSWORD: ${{ secrets.REDDIT__PASSWORD }}
  REDDIT__USERNAME: ${{ secrets.REDDIT__USERNAME }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Analyze code
        run: dotnet format --no-restore --verify-no-changes --severity info
      - name: Build
        run: dotnet build --no-restore
      - name: Run tests
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      - name: Generate code coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/coverage.cobertura.xml
          badge: false
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '75 90'
      - name: Add coverage comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
